language: java

jdk:
  - oraclejdk8

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"

addons:
  firefox: latest

script: ./gradlew test

cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
